services:
  mongodb:
    image: mongo:7.0.6
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./mongodb/mongodbData/:/data/db/
    healthcheck:
      test: ['CMD', 'echo', '''db.runCommand("ping").ok''', '|', 'mongo', 'localhost:27017/test', '--quiet']
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redisdb/redisData:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5